name: kernelviz

services:
  api:
    image: localhost/api
    environment:
      - DEBUG=false
    network_mode: host
    build:
      context: server/
      dockerfile: Containerfile.prod
    volumes:
      - ./data/:/data:z
    restart: unless-stopped
    command: gunicorn --chdir app app:app -w 2 --threads 2 -b "0.0.0.0:6000"

  nginx:
    image: docker.io/nginx:1.27-alpine
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./server/static:/www/data:z
    depends_on:
      - api
    restart: unless-stopped
