name: kernelviz

services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    volumes:
      - ./data/:/data
      - ./server/:/app
    ports:
      - 5000:5000
    stdin_open: true
    command: uv run python app.py
